name: CI (ROS Noetic)

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # Use ROS Noetic container to ensure compatible environment (Ubuntu 20.04)
    container:
      image: osrf/ros:noetic-desktop-full
    env:
      CATKIN_WS: /root/catkin_ws
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build dependencies
        shell: bash
        run: |
          set -eux
          apt-get update
          # basic tools
          apt-get install -y --no-install-recommends \
            build-essential cmake git curl gnupg lsb-release \
            python3-pip python3-vcstool python3-rosdep \
            ros-noetic-catkin ros-noetic-rosbash \
            ros-noetic-rosconsole ros-noetic-rostest \
            ros-noetic-socketcan-interface
          rm -rf /var/lib/apt/lists/*

      - name: Setup workspace
        shell: bash
        run: |
          set -eux
          mkdir -p "$CATKIN_WS/src"
          # Move repository contents into workspace src
          shopt -s dotglob
          mv * "$CATKIN_WS/src/"
          # Source ROS env for subsequent steps
          echo "source /opt/ros/noetic/setup.bash" >> $GITHUB_ENV

      - name: rosdep install
        shell: bash
        run: |
          set -eux
          source /opt/ros/noetic/setup.bash
          cd "$CATKIN_WS"
          rosdep init || true
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build (catkin_make)
        shell: bash
        run: |
          set -eux
          source /opt/ros/noetic/setup.bash
          cd "$CATKIN_WS"
          catkin_make -DCATKIN_ENABLE_TESTING=ON

      - name: Run tests
        shell: bash
        run: |
          set -eux
          source /opt/ros/noetic/setup.bash
          cd "$CATKIN_WS"
          catkin_make run_tests -j2

      - name: Collect test results
        shell: bash
        run: |
          set -eux
          source /opt/ros/noetic/setup.bash
          cd "$CATKIN_WS"
          catkin_test_results build || (cat build/*/test_results/*/*.xml; false)
